version: '2'
services: 
  jenkins-master:
    build: ./jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    extra_hosts:
      - "docker:192.168.19.134"
    links:
      - sonar
      - nexus
    volumes:
      - ./jenkins-master/var/jenkins_home:/var/jenkins_home

  sonar:
    build: ./sonar
    ports:
      - "9000:9000"
    links:
      - sonar-db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    volumes:
      - ./sonar/plugins:/opt/sonarqube/extensions/plugins

  sonar-db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./sonar/var/lib/postgresql:/var/lib/postgresql

  nexus:
    build: ./nexus
    ports:
      - "8081:8081"
    volumes:
      - ./nexus/nexus-data:/sonatype-work