version: '2'
services: 
  jenkins-master:
    build: ./devopsstack-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    extra_hosts:
      - "docker:192.168.99.100"
    links:
      - sonar
      - nexus
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - DOCKER_HOST=tcp://192.168.99.100:2376
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./devopsstack-jenkins/var/jenkins_home:/var/jenkins_home

  sonar:
    build: ./devopsstack-sonar
    ports:
      - "9000:9000"
    links:
      - sonar-db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    volumes:
      - ./devopsstack-sonar/plugins:/opt/sonarqube/extensions/plugins

  sonar-db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
#      - ./devopsstack-sonar/var/lib/postgresql/data:/var/lib/postgresql/data

  nexus:
    build: ./devopsstack-nexus
    ports:
      - "8081:8081"
    volumes:
      - ./devopsstack-nexus/nexus-data:/sonatype-work

  jira:
    build: ./devopsstack-jira
    ports:
      - '80:8080'
    links:
      - jira-db
    environment:
      - JIRA_DATABASE_URL=postgresql://jira@jira-db:5432/jira
      - JIRA_DB_PASSWORD=jira
      - CATALINA_OPTS= -Xms256m -Xmx1g
    volumes:
      - jira-data:/var/atlassian/jira
#      - ./devopsstack-jira/var/atlassian/jira:/var/atlassian/jira

  jira-db:
    image: postgres
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jira
      - POSTGRES_DB=jira
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    volumes:
      - jira-db-data:/var/lib/postgresql/data
#      - ./devopsstack-jira/var/lib/postgresql:/var/lib/postgresql

volumes:
  sonar-db-data:
    external: false
  jira-data:
    external: false
  jira-db-data:
    external: false