version: '2'
services:
  rproxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    links:
      - jenkins-master
      - sonar
      - nexus
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  jenkins-master:
    build: ./devopsstack-jenkins
    ports:
      - "50000:50000"
    links:
      - sonar
      - nexus
    environment:
      - VIRTUAL_HOST=jenkins.localhost,jenkins.blue-sharp.de
      - VIRTUAL_PORT=8080
      - JAVA_OPTS="-Djava.awt.headless=true"
    volumes:
      - jenkins-data:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
      - ./devopsstack-jenkins/users:/var/jenkins_home/users
      - ./devopsstack-jenkins/maven/.m2/settings.xml:/usr/share/jenkins/ref/.m2/settings.xml
      - ./devopsstack-jenkins/maven/.m2/settings-security.xml:/usr/share/jenkins/ref/.m2/settings-security.xml

  sonar:
    build: ./devopsstack-sonar
    links:
      - sonar-db
    environment:
      - VIRTUAL_HOST=sonar.localhost,sonar.blue-sharp.de
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    entrypoint:
      - ./bin/run.sh
    volumes:
      - sonar-data:/opt/sonarqube/extensions/plugins
  sonar-db:
    image: blacklabelops/postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

  nexus:
    build: ./devopsstack-nexus
    environment:
      - VIRTUAL_HOST=nexus.localhost,nexus.blue-sharp.de
    volumes:
      - nexus-data:/sonatype-work

volumes:
  jenkins-data:
    external: false
  sonar-data:
    external: false
  sonar-db-data:
    external: false
  nexus-data:
    external: false