version: '2'
services: 
  rproxy:
    build: ./devopsstack-rproxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - jira
      - jenkins-master
      - sonar
      - nexus

  jenkins-master:
    build: ./devopsstack-jenkins
    ports:
      - "50000:50000"
    extra_hosts:
      - "docker:192.168.99.100"
    links:
      - sonar
      - nexus
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - DOCKER_HOST=tcp://192.168.99.100:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/var/jenkins_home/.docker
    volumes:
      - jenkins-data:/var/jenkins_home

  sonar:
    build: ./devopsstack-sonar
    links:
      - sonar-db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    entrypoint:
      - ./bin/run.sh
      - -Dsonar.web.context=/sonar
    volumes:
      - sonar-data:/opt/sonarqube/extensions/plugins
  sonar-db:
    image: blacklabelops/postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

  nexus:
    build: ./devopsstack-nexus
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - nexus-data:/sonatype-work

  jira:
    build: ./devopsstack-jira
    links:
      - jira-db
    environment:
      - JIRA_DATABASE_URL=postgresql://jira@jira-db:5432/jira
      - JIRA_DB_PASSWORD=jira
      - CATALINA_OPTS= -Xms256m -Xmx1g
    volumes:
      - jira-data:/var/atlassian/jira
  jira-db:
    image: blacklabelops/postgres
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jira
      - POSTGRES_DB=jira
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    volumes:
      - jira-db-data:/var/lib/postgresql/data

volumes:
  jenkins-data:
    external: false
  sonar-data:
    external: false
  sonar-db-data:
    external: false
  nexus-data:
    external: false
  jira-data:
    external: false
  jira-db-data:
    external: false